# Generated by Django 2.2.28 on 2023-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hello_hey'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='shey',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
