# Generated by Django 2.2.28 on 2023-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_remove_hello_shey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("how", models.BigIntegerField()),
            ],
        ),
    ]
