# Generated by Django 2.2.28 on 2023-06-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hi',
            name='why',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
