# Generated by Django 2.2.28 on 2023-06-13 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_hi_why"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hi",
            name="why",
        ),
    ]
