# Generated by Django 2.2.28 on 2023-06-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_hi_why'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hi',
            name='why',
        ),
    ]
