# Generated by Django 2.2.28 on 2023-06-28 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_remove_hi_why"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hi",
        ),
    ]
