# Generated by Django 2.2.28 on 2023-07-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='hi',
        ),
        migrations.AddField(
            model_name='hello',
            name='hiii',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
