# Generated by Django 2.2.28 on 2023-07-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20230717_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='ssssdsd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
