# Generated by Django 2.2.28 on 2023-07-19 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_hello_ssssdsd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hello",
            name="ssssdsd",
        ),
    ]
